# ----------------------- #
#      Main Configs       #
# ----------------------- #


title: raise-UAV - 3D-Drucker - Drohnen - Stilvolle Luftaufnahmen - Prototyping Service - 3D-Scan und Photogrammetrie
email: info@raise-uav.com
author: Thomas Herrmann
description:  Hersteller von 3D-Druckern für die industrielle Anwendung, vielseitige Drohnen und Systeme sowie Filmproduktion spezialisiert auf Luftaufnahmen

copyright: 'Copyright &copy; 2018 raise-UAV. All Rights Reserved.'
credits: 'Credits: Based on Landing Page <a href="https://startbootstrap.com/template-overviews/landing-page/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none
baseurl: ""
url: "https://BKLronin.github.io"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram.com/raise_uav
  - title: youtube
    url: https://youtube.com/BKLronin
  - title: thingiverse
    url: https://thingiverse.com/kleingeist/designs
