# ----------------------- #
#      Main Configs       #
# ----------------------- #


title: raise-UAV - 3D-Drucker - Drohnen - Stilvolle Luftaufnahmen - Prototyping Service - 3D-Scan und Photogrammetrie
email: info@raise-uav.com
author: Thomas Herrmann
description:  Hersteller von 3D-Druckern für die industrielle Anwendung

copyright: 'Copyright &copy; 2018 raise-UAV. <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br />Diese Website ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen 4.0 International Lizenz</a>..'
credits: 'Credits: Based on Landing Page <a href="https://startbootstrap.com/template-overviews/landing-page/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none
baseurl: ""
url: "https://BKLronin.github.io"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram.com/raise_uav
  - title: youtube
    url: https://youtube.com/BKLronin
  - title: thingiverse
    url: https://thingiverse.com/kleingeist/designs
  - title: Discord
    url: https://discord.gg/Ag4jmMK
